let penyakitList = [
  {
    id: 1,
    nama: "Demam Berdarah Dengue (DBD)",
    deskripsi: "Penyakit yang disebabkan oleh virus dengue melalui gigitan nyamuk Aedes aegypti.",
    gejala: ["Demam tinggi mendadak", "Sakit kepala parah", "Nyeri di belakang mata", "Ruam kulit"],
    pengobatan: ["Istirahat cukup", "Minum banyak cairan", "Kompres demam", "Konsultasi dokter"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Tinggi",
  },
  {
    id: 2,
    nama: "Flu Biasa",
    deskripsi: "Penyakit pernapasan ringan yang disebabkan oleh virus.",
    gejala: ["Hidung tersumbat", "Demam ringan", "Bersin", "Batuk"],
    pengobatan: ["Istirahat", "Minum air hangat", "Obat flu bebas"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Rendah",
  },
  {
    id: 3,
    nama: "Malaria",
    deskripsi: "Penyakit akibat gigitan nyamuk Anopheles yang terinfeksi parasit plasmodium.",
    gejala: ["Demam berkala", "Menggigil", "Nyeri otot", "Mual"],
    pengobatan: ["Obat antimalaria", "Konsultasi dokter"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Tinggi",
  },
  {
    id: 4,
    nama: "Asma",
    deskripsi: "Penyakit kronis yang memengaruhi saluran pernapasan.",
    gejala: ["Sesak napas", "Batuk malam hari", "Mengi"],
    pengobatan: ["Inhaler", "Kontrol lingkungan", "Obat antiinflamasi"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Sedang",
  },
  {
    id: 5,
    nama: "Cacar Air",
    deskripsi: "Infeksi virus yang menyebabkan ruam kulit dengan lepuhan kecil yang gatal.",
    gejala: ["Demam ringan", "Ruam kulit", "Lepuhan berisi cairan"],
    pengobatan: ["Kompres dingin", "Losion kalamin", "Istirahat cukup"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Sedang",
  },
  {
    id: 6,
    nama: "Hipertensi",
    deskripsi: "Tekanan darah tinggi yang dapat meningkatkan risiko penyakit kardiovaskular.",
    gejala: ["Sakit kepala", "Pusing", "Detak jantung tidak teratur"],
    pengobatan: ["Diet sehat", "Olahraga rutin", "Obat antihipertensi"],
    gambar: "https://student-activity.binus.ac.id/tfi/wp-content/uploads/sites/41/2023/11/bahaya-depresi.jpeg",
    tingkatPenyakit: "Tinggi",
  },
];
